<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="interactive_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="interactive_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="interactive_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="interactive_report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="interactive_report_files/libs/quarto-html/popper.min.js"></script>
<script src="interactive_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="interactive_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="interactive_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="interactive_report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="interactive_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="interactive_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="interactive_report_files/libs/bootstrap/bootstrap-4f7cc8e85d405560d33c915fba59fd83.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">report</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduktion" class="level2">
<h2 class="anchored" data-anchor-id="introduktion">Introduktion</h2>
<p>Detta projekt analyserar orderdata från ett e-handelsföretag i syfte att ge ledningen ett bättre beslutsunderlag. Analysen fokuserar på två huvudfrågor:</p>
<ul>
<li><p><strong>Hur skiljer sig returgrad mellan olika kategorier, regioner eller kundtyper?</strong></p></li>
<li><p><strong>Finns det tecken på att längre leveranstid hänger ihop med fler returer?</strong></p></li>
<li><p><strong>Hur påverkar rabatter returgraden?</strong></p></li>
</ul>
<p>Målet är att identifiera konkreta mönster i datan som företaget kan använda för att minska returer och förbättra kundupplevelsen.</p>
</section>
<section id="fråga-1---hur-skiljer-sig-returgrad-mellan-olika-kategorier-regioner-eller-kundtyper" class="level2">
<h2 class="anchored" data-anchor-id="fråga-1---hur-skiljer-sig-returgrad-mellan-olika-kategorier-regioner-eller-kundtyper">Fråga 1 - Hur skiljer sig returgrad mellan olika kategorier, regioner eller kundtyper?</h2>
<section id="returgrad-mellan-olika-kategorier" class="level4">
<h4 class="anchored" data-anchor-id="returgrad-mellan-olika-kategorier">Returgrad mellan olika kategorier</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>returns_by_category</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  product_category count returns return_rate
  &lt;chr&gt;            &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;
1 Fashion            235      38       0.162
2 Home               207      33       0.159
3 Beauty             159      24       0.151
4 Electronics        243      32       0.132
5 Sports             156      17       0.109</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p5</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar returfrekvensen för olika produktkategorier. Fashion har den högsta returgraden (16.2%), följt av Home (15.9%) och Beauty (15.1%). Electronics har en något lägre returgrad (13.2%), medan Sports har den lägsta returgraden (10.9%).</p>
</section>
<section id="returgrad-mellan-olika-regioner" class="level4">
<h4 class="anchored" data-anchor-id="returgrad-mellan-olika-regioner">Returgrad mellan olika regioner</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>returns_by_region</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  region count returns return_rate
  &lt;chr&gt;  &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;
1 West     261      49       0.188
2 South    192      30       0.156
3 East     193      25       0.130
4 North    354      40       0.113</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>p6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar returfrekvensen för olika regioner. Regionen West har den högsta returgraden (18.8%), följt av South (15.6%) och East (13.0%). North har den lägsta returgraden (11.3%), vilket tyder på färre returer i denna region jämfört med övriga.</p>
</section>
<section id="returgrad-mellan-olika-kundtyper" class="level4">
<h4 class="anchored" data-anchor-id="returgrad-mellan-olika-kundtyper">Returgrad mellan olika kundtyper</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>returns_by_customer_type</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  customer_type count returns return_rate
  &lt;chr&gt;         &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;
1 New             245      44       0.180
2 VIP             142      19       0.134
3 Returning       613      81       0.132</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar returfrekvensen för olika kundtyper. New customers har den högsta returgraden (18.0%), följt av VIP-kunder (13.4%) och Returning customers (13.2%). Detta indikerar att nya kunder tenderar att returnera produkter oftare än mer etablerade kunder. En möjlig förklaring kan vara att nya kunder har mindre erfarenhet av produkter eller att deras förväntningar inte alltid matchar verkligheten.</p>
</section>
</section>
<section id="fråga-2---finns-det-tecken-på-att-längre-leveranstid-hänger-ihop-med-fler-returer" class="level1">
<h1>Fråga 2 - Finns det tecken på att längre leveranstid hänger ihop med fler returer?</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>returns_by_delivery</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  delivery_group count returns return_rate
  &lt;ord&gt;          &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;
1 Fast (1-2d)      232      23      0.0991
2 Medium (3-5d)    662      99      0.150 
3 Slow(6-9d)       106      22      0.208 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>p8</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar returfrekvensen baserat på olika leveransgrupper. Slow (6–9 dagar) har den högsta returgraden (20.8%), följt av Medium (3–5 dagar) med 15.0%. Fast (1–2 dagar) har den lägsta returgraden (9.9%), vilket tyder på att snabbare leveranser är kopplade till färre returer. Detta indikerar att längre leveranstider kan påverka kundnöjdheten negativt och öka sannolikheten för returer. Kunder kan bli mer otåliga eller ändra sin uppfattning om produkten när leveransen tar längre tid. Slutsatsen är att leveranstid verkar vara en viktig faktor för returbenägenhet och kundupplevelse.</p>
<section id="checking-the-avg-time-for-returned-and-not-returned-orders" class="level4">
<h4 class="anchored" data-anchor-id="checking-the-avg-time-for-returned-and-not-returned-orders">Checking the avg time for returned and not returned orders</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>shipping_vs_return</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  returned count mean_shipping_days median_shipping_days
     &lt;int&gt; &lt;int&gt;              &lt;dbl&gt;                &lt;dbl&gt;
1        0   856               3.56                    4
2        1   144               3.98                    4</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>p13</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar genomsnittlig leveranstid för ordrar som returnerats jämfört med de som inte har returnerats. Ordrar som har returnerats (Yes) har en högre genomsnittlig leveranstid på 3.98 dagar, jämfört med 3.55 dagar för ordrar som inte returnerats (No). Medianvärdet är högre för returnerade ordrar (4 dagar) jämfört med icke returnerade ordrar (3 dagar). Detta tyder på att längre leveranstider kan vara kopplade till en högre sannolikhet för returer. En möjlig förklaring är att längre väntetid kan påverka kundnöjdheten negativt. Slutsatsen är att snabbare leveranser kan bidra till att minska returer och förbättra kundupplevelsen.</p>
</section>
</section>
<section id="fråga-3---hur-påverkar-rabatter-returgraden" class="level1">
<h1>Fråga 3 - Hur påverkar rabatter returgraden?</h1>
<section id="return-rate-by-discount" class="level4">
<h4 class="anchored" data-anchor-id="return-rate-by-discount">Return rate by discount</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>return_by_discount</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  discount_tier   antal returer returgrad
  &lt;ord&gt;           &lt;int&gt;   &lt;int&gt;     &lt;dbl&gt;
1 No discount        96       9    0.0938
2 Low (1-10%)       647      87    0.134 
3 Medium (11-25%)   253      46    0.182 
4 High (25%+)         4       2    0.5   </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>p14</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar hur returgraden varierar beroende på rabattnivå. Resultatet visar ett tydligt mönster där returgraden ökar med högre rabatter. Kunden utan rabatt (No discount) har den lägsta returgraden (9.4%), Låg rabatt (1–10%) visar en något högre returgrad (13.4%), Medium rabatt (11–25%) har en ännu högre returgrad (18.2%). Hög rabatt (25%+) har den högsta returgraden (50%), men detta resultat bör tolkas försiktigt eftersom antalet observationer i denna kategori är mycket litet (endast 4 ordrar).</p>
<p>Slutsatsen är att högre rabatter kan vara kopplade till ökad returbenägenhet. En möjlig förklaring är att större rabatter kan locka mer impulsköp Samtidigt kan små urval i högsta rabattgruppen påverka resultatets tillförlitlighet.</p>
</section>
</section>
<section id="additional-analysis" class="level1">
<h1>Additional analysis</h1>
<section id="share-by-customer-segment" class="level4">
<h4 class="anchored" data-anchor-id="share-by-customer-segment">Share by customer segment</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>share_segment</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  customer_segment     n share
  &lt;chr&gt;            &lt;int&gt; &lt;dbl&gt;
1 Consumer           529 0.529
2 Small Business     302 0.302
3 Corporate          169 0.169</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar fördelningen av kunder mellan olika kundsegment. Resultatet visar att segmentet Consumer är det största (52,9%) Detta följs av Small Business (30,2%) och Corporate (16,9%). Detta indikerar att företaget främst har en konsumentdriven kundbas.</p>
</section>
<section id="share-by-customer-type" class="level4">
<h4 class="anchored" data-anchor-id="share-by-customer-type">Share by customer type</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>share_customer_type</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  customer_type     n share
  &lt;chr&gt;         &lt;int&gt; &lt;dbl&gt;
1 Returning       613 0.613
2 New             245 0.245
3 VIP             142 0.142</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Detta diagram visar fördelningen av kundtyper i datasetet. Returning customers utgör den största andelen (61.3%), följt av New customers (24.5%) och VIP customers (14.2%). Detta indikerar att återkommande kunder dominerar kundbasen.</p>
</section>
<section id="share-by-product-category" class="level4">
<h4 class="anchored" data-anchor-id="share-by-product-category">Share by product category</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>share_category</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  product_category     n share
  &lt;chr&gt;            &lt;int&gt; &lt;dbl&gt;
1 Electronics        243 0.243
2 Fashion            235 0.235
3 Home               207 0.207
4 Beauty             159 0.159
5 Sports             156 0.156</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>p3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar fördelningen av försäljning mellan olika produktkategorier. Electronics är den största kategorin (24.3%), följt av Fashion (23.5%), Home (20.7%), Beauty (15.9%) och Sports (15.6%). Detta visar att försäljningen är relativt jämnt fördelad mellan kategorierna men Electronics och Fashion dominerar något.</p>
</section>
<section id="share-by-delivery-group" class="level4">
<h4 class="anchored" data-anchor-id="share-by-delivery-group">Share by delivery group</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>share_delivery_group</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  delivery_group     n share
  &lt;ord&gt;          &lt;int&gt; &lt;dbl&gt;
1 Medium (3-5d)    662 0.662
2 Fast (1-2d)      232 0.232
3 Slow(6-9d)       106 0.106</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>p4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar fördelningen av ordrar baserat på leveranstid. Majoriteten av beställningarna tillhör kategorin Medium (3–5 dagar) med 66.2%. Därefter följer Fast (1–2 dagar) med 23.2%. Slow (6–9 dagar) utgör den minsta andelen med 10.6%.</p>
</section>
<section id="average-order-value-by-customer-segment" class="level4">
<h4 class="anchored" data-anchor-id="average-order-value-by-customer-segment">Average Order value by customer segment</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a> value_by_segment</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  customer_segment count mean_order_value median_order_value
  &lt;chr&gt;            &lt;int&gt;            &lt;dbl&gt;              &lt;dbl&gt;
1 Small Business     302             346.               162.
2 Consumer           529             322.               161.
3 Corporate          169             235.               135.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>p10</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar genomsnittligt och median ordervärde för olika kundsegment. Small Business har det högsta genomsnittliga ordervärdet (346), följt av Consumer (322).Corporate har det lägsta genomsnittliga ordervärdet (235). Medianvärdena är relativt lika mellan segmenten (cirka 135–162), vilket indikerar att skillnader i medelvärde kan påverkas av vissa höga ordervärden (outliers). Detta tyder på att Small Business-kunder tenderar att göra större köp,medan Corporate-kunder i genomsnitt handlar mindre per order. Slutsatsen är att olika kundsegment har olika köpbeteenden,vilket kan användas för att anpassa marknadsföring och erbjudanden.</p>
</section>
<section id="return-rate-by-order-value-tier" class="level4">
<h4 class="anchored" data-anchor-id="return-rate-by-order-value-tier">Return rate by order value tier</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>returns_by_order_value_tier</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  order_value_tier count returns return_rate
  &lt;ord&gt;            &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;
1 Low                250      41       0.164
2 Medium             250      39       0.156
3 High               250      30       0.12 
4 Premium            250      34       0.136</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>p9</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar returfrekvensen för olika ordervärdesnivåer. Lågprisordrar (Low) har den högsta returgraden (16.4%), följt av Medium (15.6%). Premium har en något lägre returgrad (13.6%), medan High har den lägsta returgraden (12.0%). Detta tyder på att kunder som köper billigare produkter tenderar att returnera varor oftare än kunder som köper dyrare produkter.</p>
</section>
<section id="combination-of-segment-and-customer-type-with-return-rate" class="level4">
<h4 class="anchored" data-anchor-id="combination-of-segment-and-customer-type-with-return-rate">Combination of segment and customer type with return rate</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a> returns_by_segment_type</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  customer_segment customer_type count returns return_rate
  &lt;chr&gt;            &lt;chr&gt;         &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;
1 Small Business   New              60      13      0.217 
2 Corporate        New              50       9      0.18  
3 Consumer         New             135      22      0.163 
4 Corporate        Returning       105      15      0.143 
5 Consumer         Returning       279      37      0.133 
6 Small Business   Returning       229      29      0.127 
7 Corporate        VIP              14       2      0.143 
8 Consumer         VIP             115      16      0.139 
9 Small Business   VIP              13       1      0.0769</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>p12</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar returfrekvensen uppdelat efter både kundsegment och kundtyp. Det ger en mer detaljerad bild av kundbeteendet. Bland New customers har Small Business den högsta returgraden (21.7%), följt av Corporate (18.0%) och Consumer (16.3%). Detta indikerar att nya kunder inom Small Business-segmentet är särskilt benägna att returnera produkter. För Returning customers är returgraderna generellt lägre och mer stabila, där Corporate (14.3%), Consumer (13.3%) och Small Business (12.7%) ligger nära varandra.</p>
<p>VIP-kunder visar en varierande returgrad, där Corporate (14.3%) och Consumer (13.9%) ligger på liknande nivåer, medan Small Business har en betydligt lägre returgrad (7.7%).</p>
<p>Detta tyder på att kundtyp har en stark påverkan på returbenägenhet, särskilt för nya kunder, medan mer etablerade kunder (Returning och VIP) uppvisar mer stabilt beteende. Slutsatsen är att kombinationen av kundsegment och kundtyp ger viktiga insikter, där fokus bör ligga på att minska returer bland nya kunder, särskilt inom Small Business-segmentet.</p>
</section>
<section id="shipping-days-by-region" class="level4">
<h4 class="anchored" data-anchor-id="shipping-days-by-region">Shipping days by region</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>shipping_by_region</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  region count mean_shipping_days median_shipping_days
  &lt;chr&gt;  &lt;int&gt;              &lt;dbl&gt;                &lt;dbl&gt;
1 East     193               4.47                    4
2 South    192               3.75                    4
3 West     261               3.59                    4
4 North    354               3.10                    3</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>p11</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="return-rate-by-region" class="level4">
<h4 class="anchored" data-anchor-id="return-rate-by-region">Return rate by region</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>p6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interactive_report_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tolkning</strong><br>
Diagrammet visar genomsnittlig leveranstid för olika regioner. East har den längsta genomsnittliga leveranstiden (4.47 dagar), följt av South (3.75 dagar) och West (3.59 dagar). North har den kortaste leveranstiden (3.10 dagar), vilket indikerar mer effektiva leveranser i denna region. Slutsatsen är att förbättring av leveransprocesser i vissa regioner, särskilt East, kan bidra till bättre kundupplevelse och potentiellt minska returer.</p>
</section>
<section id="section" class="level4">
<h4 class="anchored" data-anchor-id="section"></h4>
</section>
<section id="slutsatser-och-begränsningar" class="level2">
<h2 class="anchored" data-anchor-id="slutsatser-och-begränsningar">Slutsatser och begränsningar</h2>
<p>[…]</p>
</section>
<section id="metod" class="level2">
<h2 class="anchored" data-anchor-id="metod">Metod</h2>
<section id="dataförståelse" class="level3">
<h3 class="anchored" data-anchor-id="dataförståelse">1. Dataförståelse</h3>
<p>Datasetet innehåller orderdata och består av 1000 rader och 16 kolumner.</p>
<p>Numeriska variabler inkluderar exempelvis: <code>quantity</code>, <code>unit_price</code>, <code>discount_pct</code> och <code>shipping_days</code>.</p>
<p>Kategoriska variabler inkluderar: <code>customer_segment</code>, <code>customer_type</code>, <code>region</code>, <code>city</code> och <code>product_category</code>.</p>
<p>Det finns även en datumvariabel: <code>order_date</code>.</p>
<p><strong>Datasetet inehöll vissa saknade värden i variablerna:</strong></p>
<p><code>campaign_source</code> 31st, <code>discount_pct</code> 27st, <code>payment_method</code> 25st, <code>shipping_days</code> 22st och <code>city</code> 21st. Resten av variablerna saknade inga värden.</p>
<p><strong>För vår analys och valda frågeställningar om returgrad</strong> <strong>och leveranstid, är följande variabler särskilt viktiga:</strong></p>
<p><code>returned</code> = om ordern returnerats</p>
<p><code>shipping_days</code> = leveranstid</p>
<p><code>product_category</code>, <code>region</code>, <code>customer_type</code> = jämförelser mellan grupper</p>
<p>Används för att analysera returgrad och samband med leveranstid.</p>
</section>
<section id="datastädning-och-förberedelse" class="level3">
<h3 class="anchored" data-anchor-id="datastädning-och-förberedelse">2. Datastädning och förberedelse</h3>
<p>Datarensningen och förberedelsen av data gick igenom tre steg: standardisering och korrigering av data, hantering av saknade värden samt skapande av nya variabler.</p>
<p><strong>Standardisering</strong><br>
I det första steget standardiserades kolumner för att säkerställa att datan var konsekvent:</p>
<ul>
<li><p><code>order_id</code> och <code>customer_id</code> rensades från mellanslag och gjordes om till versaler, eftersom samma order annars kunde ha räknats som två olika om den stavades på olika sätt.</p></li>
<li><p><code>order_date</code> konverterades till date format så att det går att sortera och räkna på datum.</p></li>
<li><p><code>city</code>korrigerades manuellt för att hantera svenska specialtecken, annars hade samma stad dykt upp som flera olika städer i analysen.</p></li>
<li><p><code>campaign_source</code> och <code>payment_method</code> rengjordes på samma sätt.</p></li>
<li><p><code>returned</code> gjordes om från text (Yes/No) till siffror (1/0) för att kunna räkna ut returfrekvenser.</p></li>
</ul>
<p><strong>Hantering av saknade värden</strong><br>
För kategoriska kolumner som saknade värden (<code>city</code>, <code>campaign_source</code>, <code>payment_method</code>) fylldes dem i med det vanligaste förekommande värdet i respektive kolumn.</p>
<p>För numeriska kolumner (<code>shipping_days</code>, <code>discount_pct</code>) användes medianen istället för medelvärdet, eftersom medianen påverkas mindre av extremvärden och därför ger en mer representativ bild av datan.</p>
<p><strong>Nya variabler</strong><br>
Fyra nya variabler skapades för att berika analysen:</p>
<ul>
<li><p><code>order_value</code> beräknar det faktiska ordervärdet efter rabatt.</p></li>
<li><p><code>order_value_tier</code> delar in orders i fyra nivåer (Low, Medium, High och Premium) baserat på värde.</p></li>
<li><p><code>delivery_group</code> grupperar leveranstiden i kategorier från snabb till mycket långsam.</p></li>
<li><p><code>discount_tier</code> delar in rabatten i nivåer från ingen rabatt till hög rabatt.</p></li>
</ul>
<p>Dessa variabler gör det enklare att se mönster och jämföra grupper i analysen.</p>
</section>
<section id="statistiska-sammanfattningar" class="level3">
<h3 class="anchored" data-anchor-id="statistiska-sammanfattningar"><strong>3. Statistiska sammanfattningar</strong></h3>
<p>Datasetet innehåller 1 000 ordrar från 255 unika kunder fördelade över 5 produktkategorier.</p>
<p><strong>Numeriska nyckeltal:</strong></p>
<p>Medelvärdet för ordervärde <code>order_value</code> var 314 kr, medan medianen låg på 152 kr. Den stora skillnaden tyder på att ett antal höga ordrar drar upp medelvärdet.</p>
<p>Genomsnittligt antal produkter per order <code>quantity</code> var 1,36 med en median på 1.</p>
<p><strong>Andelar:</strong> - <em>Kundsegment:</em> <code>Consumer</code> utgjorde den största gruppen (52,9%), följt av <code>Small Business</code> (30,2%) och slutligen <code>Corporate</code> (16,9%).</p>
<ul>
<li><p><em>Kundtyp:</em> <code>Returning</code> klart största typ med (61,3%), följt av <code>New</code> (24,5%) och <code>VIP</code> (14,2%).</p></li>
<li><p><em>Produktkategori:</em> <code>Electronics</code> (24,3%) och <code>Fashion</code> (23,5%) var de största kategorierna, följt av <code>Home</code> (20,7%), <code>Beauty</code> (15,9%) och <code>Sports</code> (15,6%).</p></li>
<li><p><em>Leveranstid:</em> Den vanligaste leveranstiden för kunder är <code>Medium (3-5d)</code> (66,2%), följt utav <code>Fast (1-2d)</code> (23,2%) och till sist <code>Slow(6-9d)</code> med (10.6%).</p></li>
</ul>
<p><strong>Returgrad och gruppjämförelser:</strong> Den totala returgraden var 14,4%.</p>
<ul>
<li><p><em>Per produktkategori:</em> <code>Fashion</code> hade högst returgrad (16,2%), följt av <code>Home</code> (15,9%) och <code>Beauty</code> (15,1%). <code>Sports</code> hade lägst returgrad (10,9%).</p></li>
<li><p><em>Per region:</em> <code>West</code> hade klart högst returgrad (18,8%), medan <code>North</code> hade lägst (11,3%).</p></li>
<li><p><em>Per kundtyp:</em> Nya kunder (<code>New</code>) returnerade oftast (18,0%), jämfört med <code>VIP</code> (13,4%) och <code>Returning</code> (13,2%).</p></li>
<li><p><em>Per leveransgrupp:</em> Långsammare leverans hänger ihop med fler returer — <code>Slow (6–9 dagar)</code> hade (20,8%) returgrad, <code>Medium   (3–5 dagar)</code> (15,0%) och <code>Fast (1–2 dagar)</code> (9,9%).</p></li>
<li><p><em>Per ordervärde:</em> Baserat på tiering <code>order_value_tier</code> så är det lite vanligare att mindre ordrar oftare returneras. <code>Low</code> (16,4%) och <code>Medium</code> (15.6%) ligger något högre jämfört med <code>Premium</code> (13,6%) och <code>High</code> (12%)</p></li>
</ul>
<p><strong>Ordervärde per kundsegment:</strong> <code>Small Business</code> hade högst genomsnittligt ordervärde (346 kr), följt av <code>Consumer</code> (322 kr) och <code>Corporate</code> (235 kr).</p>
<p><strong>Leveranstid per region:</strong> <code>East</code> hade längst genomsnittlig leveranstid (4,5 dagar), medan <code>North</code> hade kortast (3,1 dagar). <code>South</code> och <code>West</code> låg däremellan (3,8 respektive 3,6 dagar).</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>